#ifndef NEWFITS_H_
#define NEWFITS_H_

// write a brand new output fits file
// either automatically creating a minimalistic header
// or retreiving an exsiting one from another file

//inputs: the number of columns and rows in pixels, the 2d image array,
//the (null terminated) name of the output file
//get_head = 1 if a header should be retreived from another file with name r_file
//fresh_head = 0 (or anything not 1) if a fresh, automatic header should be
//        generated by fitsio

void newfits_(int nx, int ny, int** pic, char* w_file, int get_head, char* r_file);

#endif
